### ISSUE TITLE
Increase sleep time when 429 error occurs 

### ISSUE THREAD

**Issue by bruvv** [ohld/igbot#1182]
### Purpose of your issue?
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

--- 

### Describe your issue

When we hit a 429 error because something went to wrong and we got soft banned. A 5 minute sleep will be initiated. After 5 minutes it will be tried again. If we are still soft banned, we have another 5 minutes of sleep.
What I want to do but I am unable to make myself is that if a second time this sleep occurs, add 5 minutes to it so the timer creeps up. First time it is 5 minutes, second time it is 10 minutes etc...

I tried to change this line:
https://github.com/instagrambot/instabot/blob/master/instabot/api/api.py#L491
To: (added the + sign)
```
sleep_minutes += 5
```
but that didn't work.

**Comment by uzairzia** [comment]
@bruvv One thing you could do is add an argument in the function definition of `send_request()` that passes the current sleep_minutes to the recursively called `send_request()`.
Something like this: 

[Function Definition](https://github.com/instagrambot/instabot/blob/master/instabot/api/api.py#L405)
```
def send_request(  # noqa: C901
        self,
        endpoint,
        post=None,
        login=False,
        with_signature=True,
        headers=None,
        extra_sig=None,
        sleep_minutes=None,
    ):
```
****
Since the first time that the function is called, `sleep_minutes` will most likely be `None`. Therefore:
[Somewhere Here](https://github.com/instagrambot/instabot/blob/master/instabot/api/api.py#L491)
```
if sleep_minutes is None:
        sleep_minutes = 0

sleep_minutes = sleep_minutes + 5
```
****
In the where the function is recursively called,
[Recursive Call](https://github.com/instagrambot/instabot/blob/master/instabot/api/api.py#L497)
```
return self.send_request(
                    endpoint, 
                    post, 
                    login, 
                    with_signature, 
                    headers, 
                    extra_sig, 
                    sleep_minutes
                )
```

**Comment by bruvv** [comment]
That is a very good one. I made a PR thanks. https://github.com/instagrambot/instabot/pull/1199
