### ISSUE TITLE
Logging not enough - need more specific details if a user not followed

### ISSUE THREAD

**Issue by tayfunyasar** [ohld/igbot#178]
I'm importing a username list, but my robot not follow some of them. And I don't know why.

Thanks.

**Comment by ohld** [comment]
This users were filtered. Read the filtration conditions how robot does it.

**Comment by tayfunyasar** [comment]
Yes but why? :) in which conditions? We need to set logging level & do it configurable.

**Comment by alexroan** [comment]
https://github.com/instagrambot/instabot/blob/master/instabot/bot/bot_follow.py 

I think line 10 in the bot_follow.py should return false instead of true. 

```py
    if not self.check_user(user_id):
        return True
```

should be:

```py
    if not self.check_user(user_id):
        return False
```

This is likely where the issue is occurring. The bot fails when checking the user with the filtering, yet follow(self, user_id) returns True as if the user was followed.

**Comment by ohld** [comment]
@alexroan Please test this correction and if it is solve the issue make the pull request and i'll merge it. Thanks.

**Comment by ohld** [comment]
Reopen if have not solved yet.
