### ISSUE TITLE
How to modify files?

### ISSUE THREAD

**Issue by michaelgenty** [ohld/igbot#181]
Hi,
I think I must miss something, but I want to modify "bot_filter.py", especially to invert the list "get_user_following".
But the changes are not taken in charge, can someone explain me why?

Many thanks :)

**Comment by ohld** [comment]
Because you installed instabot via pip in your system. So you change files that not used. 
Try: `pip uninstall instabot`
After you done this instabot will use source files you changed. But you should understand that if you change something it probably wouldn't work if you are not fluent with python!

**Comment by michaelgenty** [comment]
Ok, thanks for the answer :)
I think it will not be a problem to reverse a list :)
