### ISSUE TITLE
follow_users_from_file.py not continuing where it left

### ISSUE THREAD

**Issue by tayfunyasar** [ohld/igbot#183]
it always starts at index 0.

Thanks

**Comment by ohld** [comment]
The script should skip users who is already followed.

**Comment by tayfunyasar** [comment]
What about this error?

> 2017-05-18 22:17:56,272 - INFO - Going to follow 54490 users.
>   0%|                                                                                                                                                                                                                                      | 4/54490 [00:22<88:32:53,  5.85s/it]2017-05-18 22:18:19,773 - WARNING - Request return 404 error!
> 2017-05-18 22:18:24,967 - WARNING - Request return 404 error!
> 2017-05-18 22:18:34,969 - INFO - DONE: Total followed 4 users.
> 2017-05-18 22:18:35,332 - INFO - Bot stopped. Worked: 0:00:37.918335
> 2017-05-18 22:18:35,332 - INFO - Total followed: 4
> 2017-05-18 22:18:35,333 - INFO - Total requests: 262
> Tayfuns-MacBook-Pro-2:instabot tayfunyasar$

**Comment by sweb1** [comment]
I get the same error when following users from file:

2017-07-25 21:46:47,285 - INFO - Going to follow 825 users.
  2%|█▎                                                                             | 14/825 [07:11<6:43:41, 29.87s/it]2017-07-25 21:53:58,609 - WARNING - Request return 404 error!
2017-07-25 21:54:22,170 - WARNING - Request return 404 error!
2017-07-25 21:54:32,172 - INFO - DONE: Total followed 19 users.
2017-07-25 21:54:32,460 - INFO - Bot stopped. Worked: 0:13:35.941472
2017-07-25 21:54:32,460 - INFO - Total followed: 19
2017-07-25 21:54:32,461 - INFO - Total requests: 2017

Script should skip users that are not existing and continue with next entry instead of stopping.

**Comment by ohld** [comment]
If you found the solution please make the pull request.
