### ISSUE TITLE
[auto_post.py] Request return 400 error on image upload.

### ISSUE THREAD

**Issue by theritvars** [ohld/igbot#221]
While trying to use ```auto_post.py``` I was unable to post any images due to the script returning an 400 error. What is the issue here?

Console output:
```
2017-05-27 14:29:57,902 - INFO - Login success as blah!
Can't find 'whitelist.txt' file.
Can't find 'friends_blah.txt' file.
Can't find 'friends_5372200227.txt' file.
Can't find 'friends.txt' file.
upload: Sweet #blah #blah2 #blah1
2017-05-27 14:29:59,359 - WARNING - Request return 400 error!
<Response [400]>
upload: Sweet #blah #blah2 #blah1
2017-05-27 14:31:00,516 - WARNING - Request return 400 error!
<Response [400]>
```

**Comment by skawm** [comment]
Since i'm working on Instagram automation I have encountered many times this lovely 400 error. 
It's an Instagram limitation, you have uploaded too many pics/videos during your development. You are now a spammy account. What you can do is change account and optionally use a proxy (only private proxy, not public).
Or just wait a bit (maybe 1 day at least I would say.. I don't know exactly)

**Comment by theritvars** [comment]
@skawm That's the thing. I haven't. My account only has 4 pictures, and I wanted to get the auto post working, but as soon as I tried I got this error.

**Comment by ohld** [comment]
400 error sometimes mean that the request isn't done properly. I think the problem is that instagram changed it's API or we have a bug.

**Comment by ehthxC7x9D** [comment]
@RichusX There are so many different reasons for 400, it's a bit of a catch all.  I personally ran in to it when I was trying to post images that were not the proper dimensions. IG is pretty picky about image dimensions.

**Comment by ohld** [comment]
Reopen if you still have not found the solution (don't forget to update the bot).
