### ISSUE TITLE
Filtering by stop words in the description

### ISSUE THREAD

**Issue by JMnemonick** [ohld/igbot#35]
For example:
"stop_words_list=['shop', 'gain', 'followers']

**Comment by DrCherry** [comment]
So a blacklist for words, tags, etc.

**Comment by ohld** [comment]
I think the idea was to create stop words for 

- user's info (e.g. to filter the shop's accounts)
- usernames 
- may be used hashtag 
- may be used geolocation

**Comment by ohld** [comment]
Done un 0.3.3.4

**Comment by mwargan** [comment]
Does this also look for the terms in hashtags inside each media post? I looked through the code and with my non-existent python skills it didn't look like it... any way we could do that?

**Comment by Lando-L** [comment]
@mwargan Yes that would be very helpful. I was looking for the same thing. For now it seams the stop words are only searched within the profile description. So using the `like_hashtag` method it can happen that you like pictures tagged with hashtags included the stop words, because they are not present in the profile.
