### ISSUE TITLE
Request : Filtering features

### ISSUE THREAD

**Issue by jslm** [ohld/igbot#408]
Hi there,
When follow or like functions by hashtag : 
Would be great to add these filters (and to be able to combines them together) :

- Gender (male/female)
- (AND/OR) Words/phrase in caption
- (AND/OR) Mention (@user)
- (AND/OR) Profil (bio)

Let me know!

**Comment by sudoguy** [comment]
instagram does not store the user's gender.
But filtering by word in caption and profile can be done

**Comment by Fardinak** [comment]
I would also like to see said filters, but I believe implementing middleware-based filtering could be a better idea since…

- it would leave the code cleaner
- allow custom filters (no need for updating the library)
- allow complicated filters that would never make it into the library

i.e. I imagine being able to use the [Clarifai](https://clarifai.com/) API to filter irrelevant and NSFW content (also selective automatic reposting and smart commenting, although that's another discussion)

A helper module could provide the most common filters for profiles and media, ready to be used with minimal configuration. I would be willing to contribute the code for middleware support, provided that you see it fit for a novice Python developer.

**Comment by bruvv** [comment]
Closing this since its a very old issue. If this is still an issue please open a new one.
