### ISSUE TITLE
More people followed than expected

### ISSUE THREAD

**Issue by pl4giat** [ohld/igbot#808]
[x ] Updated to the latest version
    [x ] Read the README and docs
    [x ] Searched the bugtracker for similar issues including closed ones

Purpose of your issue?

Bug report (encountered problems/errors)
Feature request (request for a new functionality)
[x ] Question

Paste the output of python -V here: Python 2.7.15+, Python 3.6.7

Describe your issue

Hello all ! I have a problem with the ultimate.py code. I only use the "follow_followers function). I want to follow a little amount of people like 30 but when i run some test with, for example, 5 max_follows_per_day, the code stops after "following" 5 people but when i check my instagram account, i got 12 or 18 followers instead of 5. (I was at 0 followers at the beginning of my test).

Can we solve this ?

**Comment by djtroi** [comment]
Is it possible that the bot makes follow requests on some users, and they accept it later / on the next day? 

Try to filter out private profiles and test it again.

**Comment by ohyesohyes** [comment]
I strongly believe no matter how you set the bot, this follows and likes particular group of people that the admins (bot makers) want. Yet this is a scam. Also that is why there is no fix for the bot mode as well. It only works as is. Try setting the bot follow 50 unfollow 50, see it does not unfollow. This needs to be reported, as this is a way of stealing peoples passwords.

**Comment by ohld** [comment]
@ohyesohyes Your message was so funny, thank you for it!

Our bot has a lot of bugs since Instagram is frequently changing their bot protection systems. That is why some features may fail. Personally, I don't have time to fix them all. If you know how to fix them, please make a pull request - I'll add your code to the main repository if it passed all the code style checks and unit tests.

Also, seems like you don't understand what an open source project is. The source code of the bot is placed in this repository, you can manually check every line of it and see that it does only what is coded. if you don't believe in the compiled version that was uploaded to `pip` - feel free to build the project from source files by yourself.

Have a nice day!
